# title of website
title: hentai

# description of website
description: g3nt1eman's navigation site

# favicon of website
favicon: "https://github.com/g3nt1eman.png?size=40"

# your website url
url: https://g3nt1eman.github.io/hentai/


# footer message
footer: © 2021-2021 @g3nt1eman

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

webstack:


content:
  categories:
    - name: 工具
      sites:
        - name: Greasy Fork
          url: https://greasyfork.org/zh-CN
         - name: Sleazy Fork
          url: https://sleazyfork.org/zh-CN
        - name: Telegraph
          url: https://telegra.ph/
          
    - name: 收藏
      sites:
        - name: 寝取り・寝取られ・NTR エロ動画 - Javmix.TV
          url: https://javmix.tv/genre/%e5%af%9d%e5%8f%96%e3%82%8a%e3%83%bb%e5%af%9d%e5%8f%96%e3%82%89%e3%82%8c%e3%83%bbntr/
        - name: 脱獄者 エロ動画 - Javmix.TV
          url: https://javmix.tv/series/%e8%84%b1%e7%8d%84%e8%80%85/
        - name: ドラマ エロ動画 - Javmix.TV
          url: https://javmix.tv/genre/%e3%83%89%e3%83%a9%e3%83%9e/
        - name: 自拍套圖 | AVbebe
          url: https://avbebe.com/archives/category/%e8%87%aa%e6%8b%8d%e5%a5%97%e5%9c%96
        - name: 逃犯AV在線看 - Jable.TV | 免費高清AV在線看 | J片 AV看到飽
          url: https://jable.tv/tags/fugitive/
        - name: 強姦AV在線看 - Jable.TV | 免費高清AV在線看 | J片 AV看到飽
          url: https://jable.tv/tags/rape/
        - name: 松鼠症仓库-NTR/人妻单行本列表 -页数 1
          url: https://ahri-hentai.com/dnew.php?category_id=1&t=1617206400&tag_id=16&tag_id2=23&sort=d.sort_order&order=DESC
        - name: 死亡与夜晚邪恶色情影片 - Javmix.TV
          url: https://zh-cn.javmix.tv/label/%e6%ad%bb%e5%a4%9c%e6%82%aa/
        - name: 攻击者色情影片 - Javmix.TV
          url: https://zh-cn.javmix.tv/maker/%e3%82%a2%e3%82%bf%e3%83%83%e3%82%ab%e3%83%bc%e3%82%ba/

    - name: 漫画
      sites:
        - name: 禁漫天堂
          url: https://18comic.vip/
        - name: 松鼠症仓库
          url: https://ahri8.top/
        - name: exhentai
          url: https://exhentai.org/
        - name: e-hentai
          url: https://forums.e-hentai.org/
        - name: ExHentai.org
          url: https://exhentai.org/?page=85&f_search=%22language:chinese%22+%22female:mother%22+
        - name: 合集 - 頁數 1 - 松鼠症倉庫
          url: https://ahri8.top/dnew.php?author_id=10508&t=1701360000
          
    - name: 写真
      sites:
        - name: アイドル・芸能人 エロ動画 - Javmix.TV
          url: https://javmix.tv/genre/%e3%82%a2%e3%82%a4%e3%83%89%e3%83%ab%e3%83%bb%e8%8a%b8%e8%83%bd%e4%ba%ba/

    - name: 小说
      sites:
        - name: 疯情书库
          url: https://aabook.xyz/
        - name: 禁忌书屋
          url: https://www.cool18.com/bbs4/index.php
        - name: 我的美母教师刘雨
          url: http://bc-bc.site/forum.php?mod=viewthread&tid=8703681&extra=page%3D1%26filter%3Dauthor%26orderby%3Ddateline%26orderby%3Ddateline
          
    - name: 有声
      sites:
        - name: Chinese Language 【中国語】 – Japanese ASMR
          url: https://japaneseasmr.com/tag/chinese-language/
        - name: 芭芭拉有声小说网
          url: http://www.8ysxs.top/Index.Html
        - name: ASMR基佬中心
          url: https://www.asmrgay.com/
        - name: ASMRS生活
          url: https://asmrs.live/
        - name: 细语阁有声小说
          url: http://xiyuge.info/
        - name: 柒柒音声吧
          url: https://www.qiqijie8.uk/

    - name: 三级
      sites:
        - name: 劇迷X GimyX
          url: https://gimyx.com/

    - name: 在线视频
      sites:
        - name: Javmix.TV
          url: https://javmix.tv/
        - name: AVbebe
          url: https://avbebe.com/
        - name: Jav777在线中文字幕
          url: https://www.jav777.xyz/page/1
        - name: Jable.TV
          url: https://jable.tv/
        - name: JAV線上看
          url: https://hpjav.tv/tw/
        - name: 小林ひとみの動画 976件 - 動画エロタレスト
          url: https://movie.eroterest.net/?word=%E5%B0%8F%E6%9E%97%E3%81%B2%E3%81%A8%E3%81%BF
        - name: Fc2 live - Indoxtube
          url: http://178.128.25.172/tag/fc2-live
        - name: Free Watch JAV Online, Free Download HD JAV. 毎日更新 無料アダルトAV動画,無修正エロ動画
          url: https://popjav.tv/
        - name: 脱裤吧
          url: https://www.tkbyvi.life/

    - name: 论坛
      sites:
        - name: 草榴社區
          url: http://t66y.com/index.php
        - name: SexInSex
          url: http://sexinsex.net/bbs/index.php
        - name: SiS001
          url: https://sis001.com/forum/index.php
         - name: 草榴社區
          url: http://t66y.com/index.php         
         - name: 1024核工厂
          url: http://1024xp.com/  
        - name: 2048核基地
          url: https://m1.lto5.xyz/2048/
        - name: 比思論壇
          url: http://hkbisi.com/
        - name: 杏吧
          url: https://sex8.cc/forum.php
        - name: 南+ South Plus
          url: https://www.south-plus.net/

    - name: 图片
      sites:
        - name: 图片
          url: https://sldlxz.com/
        - name: Sharesome
          url: https://sharesome.com/news
        - name: Fapello
          url: https://fapello.com/search/
        - name: Waptap
          url: https://waptap.com/
        - name: 裸体视频名人
          url: https://videocelebs.net/
        - name: 裸体明星，裸体照片。 花花公子和狗仔队的照片。 视频、假货和 OnlyFans
          url: https://celeb.gate.cc/

    - name: 资讯
      sites:
        - name: JAVLibrary
          url: http://www.javlibrary.com/cn/
        - name: JavDB 成人影片數據庫
          url: https://javdb.com/
        - name: 福利吧
          url: https://fuliba2023.net/
        - name: Porn Dude
          url: https://theporndude.com/zh
        - name: AVNo.1
          url: http://www.playno1.com/portal.php?mod=list&catid=78
        - name: 黑料不打烊
          url: https://zztt04.com/

    - name: AV导演
      sites:
        - name: 菅原養史 所执导的影片 - JAVLibrary
          url: https://www.javlibrary.com/cn/vl_director.php?d=aaya
        - name: 貞邪我 所执导的影片 - JAVLibrary
          url: https://www.javlibrary.com/cn/vl_director.php?d=jqrq
        - name: 和泉湧水 所执导的影片 - JAVLibrary
          url: https://www.javlibrary.com/cn/vl_director.php?d=inhq
        - name: さだおかさだお 所执导的影片 - JAVLibrary
          url: https://www.javlibrary.com/cn/vl_director.php?d=o47q

    - name: 直播
      sites:
        - name: FC2 Live 成人频道
          url: https://livechatfc2.com/adult/












          





